version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: /app
    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Build the project
      - run:
          name: Build
          command: dotnet build

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    working_directory: /app
    steps:
      - checkout

      # Restore dependencies
      - run:
          name: Restore Dependencies
          command: dotnet restore

      # Run tests
      - run:
          name: Run Tests
          command: dotnet test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
